_BASE_: "./faster_rcnn_R50_bdd100k.yaml"

# NOTE: this must be 9 to fit current model
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 9

SEMISUPNET:
  BURN_UP_STEP: 100000 # NOTE: set this as MAX_ITER

DATASETS:
  TRAIN_LABEL: ("bdd100k_train",)  # NOTE: all train
  TEST: ("bdd100k_val",)  # NOTE: all val

VANISHING_POINT: "/home/aghosh/Projects/2PCNet/Datasets/VP/bdd100k_all_vp.json" # NOTE: all vps

NIGHTAUG: False
STUDENT_SCALE: False
CONSISTENCY: False

# USE_DEBUG: True



