# TODO: add configs for curriculum learning
_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res5"]
    RES5_DILATION: 2
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    IN_FEATURES: ["res5"]
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    IN_FEATURES: ["res5"]
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 10
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (90000, 120000, 135000, 540000) # NOTE: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  # NOTE: extrapolate to 150k now because splitting stages
  MID_ITER: 150000  # NOTE: 100000
  MAX_ITER: 225000  # NOTE: 150000
  IMG_PER_BATCH_LABEL: 12 # NOTE: 18
  IMG_PER_BATCH_UNLABEL: 12 # NOTE: 18
  BASE_LR: 0.04
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("bdd100k_day_train",) #voc_2012_train

  # NOTE: add cur learning seq here
  CUR_LEARN_SEQ: True
  TRAIN_LABEL_MID: ("bdd100k_day_train_mid",)

  TRAIN_UNLABEL: ("bdd100k_night_train",) #Clipart1k_train
  TEST: ("bdd100k_night_val",) #Clipart1k_test
  TRAIN_UNLABEL_DEPTH: ("bdd100k_night_train_depth",)

  
SEMISUPNET:
  Trainer: "studentteacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 75000 # NOTE: 50000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.3
  SUP_LOSS_WEIGHT: 1.0
  SCALE_LIST: (0.5, 0.6, 0.7,0.8,0.9,1.0)
  SCALE_STEPS: (85500, 96000, 106500, 117000, 127500,  138000) # NOTE: (57000,64000,71000,78000,85000,92000)
TEST:
  EVAL_PERIOD: 2000
NIGHTAUG: True
STUDENT_SCALE: True
CONSISTENCY: True

# USE_DEBUG: True
# TWO_PC_AUG: False
# AUG_PROB: 1.0
# USE_TGT_DEBUG: True