# NOTE: use another yaml to reduce code
_BASE_: "./bdd100k_warp_aug_9_11_4090.yaml"

# NOTE: train on clear, adapted to rainy, test on rainy

# NOTE: change the unsup and test data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DATASETS:
  TRAIN_LABEL: ("bdd100k_clear_train_valid_vp",)
  # TRAIN_UNLABEL: ("bdd100k_rainy_train",) #Clipart1k_train
  # TEST: ("bdd100k_rainy_val",) #Clipart1k_test
  TRAIN_UNLABEL: ("acdc_train",) #Clipart1k_train
  # TEST: ("acdc_val_fog",) #Clipart1k_test
  # TEST: ("acdc_val_night",) #Clipart1k_test
  # TEST: ("acdc_val_rain",) #Clipart1k_test
  # TEST: ("acdc_val_snow",) #Clipart1k_test
  TEST: ("acdc_val",) #Clipart1k_test

# NOTE: decrease the max_iter and the steps!!!!!!!!!!!!!!!!!!!!!!!!!
SOLVER:
  # STEPS: (72000, 96000, 108000, 432000)
  STEPS: (66000, 68000, 108000, 432000)
  MAX_ITER: 70000

# NOTE: adjust SCALE_STEPS here!!!!!!!!!!!!!!!!!!!
SEMISUPNET:
  BURN_UP_STEP: 60000
  # SCALE_STEPS: (68400, 76800, 85200, 93600, 102000, 110400) # [8400, 16800, 25200, 33600, 42000, 50400]
  # ACDC has 1.6k images, whereas bdd100k has 100k images. So, we need to scale the steps accordingly.
  SCALE_STEPS: (61400, 62800, 64200, 65600, 67000, 68400) # [1400, 2800, 4200, 5600, 7000, 8400]

VANISHING_POINT: "/home/aghosh/Projects/2PCNet/Datasets/VP/train_clear.json"

# PATH_BLUR: True
WARP_AUG_LZU: False


# USE_DEBUG: True
# TWO_PC_AUG: False
# AUG_PROB: 1.0
# WARP_DEBUG: True
NIGHTAUG: False
