## Usage: Train on BDD100 Clear and Tesla Annotated, Test on Tesla Annotated
## No adaptation involved.

_BASE_: "./bdd100k_10_18_baseline.yaml"
DATASETS:
  TRAIN_LABEL: ("bdd100k_clear_train_valid_vp_vehicles_merged", "tesla_annotated_train_vehicles_merged") #("bdd100k_clear_train_valid_vp",)
  TEST: ("tesla_annotated_test_vehicles_merged",) #("bdd100k_rainy_val",) #Clipart1k_testi

# NOTE: stop training once supervised stage ends
SOLVER:
  STEPS: (144000, 192000, 216000, 864000)  # ensure supervised stage does not use these
  MAX_ITER: 120001  # end right after the supervised stage

SEMISUPNET:
  BURN_UP_STEP: 120000  # Double the original value
  SCALE_STEPS: (128400, 136800, 145200, 153600, 162000, 170400) # ensure supervised stage does not use these