_BASE_: "./bdd100k_10_1.yaml"

VANISHING_POINT: "/home/aghosh/Projects/2PCNet/Datasets/VP/bdd100k_all_vp.json"

WARP_AUG_LZU: True
WARP_FOVEA: True

WARP_AUG: True

# USE_DEBUG: True
# WARP_DEBUG: True
