# NOTE: use another yaml to reduce code
_BASE_: "./bdd100k_10_18_baseline.yaml"

# NOTE: use tpp now for debug

WARP_AUG_LZU: True
# WARP_FOVEA_INST: True
# WARP_DEBUG: True

SOLVER:
  STEPS: (72000, 96000, 108000, 432000)
  MAX_ITER: 120000
  IMG_PER_BATCH_LABEL: 5 # 15
  IMG_PER_BATCH_UNLABEL: 5 # 15