_BASE_: "./faster_rcnn_R50_bdd100k.yaml"

SOLVER:
  STEPS: (72000, 96000, 108000, 432000)
  MAX_ITER: 60000 # NOTE: should be same as BURN_UP_STEP
  IMG_PER_BATCH_LABEL: 15 # 15
  IMG_PER_BATCH_UNLABEL: 15 # 15

SEMISUPNET:
  BURN_UP_STEP: 60000
  SCALE_STEPS: (68400, 76800, 85200, 93600, 102000, 110400)

DATASETS:
  TRAIN_LABEL: ("bdd100k_night_train",)  # NOTE: should be night images

# advanced stuffs => adjust based on your needs

VANISHING_POINT: "/home/aghosh/Projects/2PCNet/Datasets/VP/bdd100k_all_vp.json" # NOTE: all vps
# WARP_AUG_LZU: True # TODO: change later

# PATH_BLUR: True

# USE_DEBUG: True
# TWO_PC_AUG: False
# AUG_PROB: 1.0
# WARP_DEBUG: True

NIGHTAUG: False # NOTE: should be False