# NOTE: use another yaml to reduce code
_BASE_: "./bdd100k_warp_aug_9_11_4090.yaml"

WARP_AUG_LZU: True
WARP_MIDDLE: True

# PATH_BLUR: True

# USE_DEBUG: True
# TWO_PC_AUG: False
# AUG_PROB: 1.0
# WARP_DEBUG: True