# NOTE: use another yaml to reduce code
_BASE_: "./bdd100k_10_18_baseline.yaml"

# TODO: change supervised label so it only include small objects

# NOTE: first debug this, then change to this
DATASETS:
  TRAIN_LABEL: ("bdd100k_clear_train_small_valid_vp",)

# NOTE: only want supervised stage for now
SOLVER:
  MAX_ITER: 60000