# NOTE: use another yaml to reduce code
_BASE_: "./bdd100k_warp_aug_9_11_4090.yaml"

# NOTE: train on clear, adapted to rainy, test on rainy

# NOTE: change the unsup and test data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DATASETS:
  TRAIN_LABEL: ("bdd100k_clear_train_valid_vp",)
  TRAIN_UNLABEL: ("dense_snow_train",) #Clipart1k_train
  TEST: ("dense_snow_val",) #Clipart1k_test

# TODO: adjust the stuffs below based on the new dataset
# NOTE: decrease the max_iter and the steps!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: use this because currently no GPU left
SOLVER:
  STEPS: (65000, 75000, 80000, 432000)
  IMG_PER_BATCH_LABEL: 10 # 15
  IMG_PER_BATCH_UNLABEL: 10 # 15
  MAX_ITER: 97500

# NOTE: adjust SCALE_STEPS here!!!!!!!!!!!!!!!!!!!
SEMISUPNET:
  SCALE_STEPS: (65250, 70500, 75750, 81000, 86250) # [5250, 10500, 15750, 21000, 26250, 31500]

VANISHING_POINT: "/home/aghosh/Projects/2PCNet/Datasets/VP/train_clear.json"

# PATH_BLUR: True
WARP_AUG_LZU: False


# USE_DEBUG: True
# TWO_PC_AUG: False
# AUG_PROB: 1.0
# WARP_DEBUG: True
NIGHTAUG: False
