# NOTE: use another yaml to reduce code
_BASE_: "./bdd100k_warp_aug_9_11_4090.yaml"

# NOTE: train on clear, adapted to rainy, test on rainy

# NOTE: change the unsup and test data!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DATASETS:
  TRAIN_LABEL: ("bdd100k_clear_train_valid_vp",)
  TRAIN_UNLABEL: ("dense_foggy_train",) #Clipart1k_train
  TEST: ("dense_foggy_val",) #Clipart1k_test

# NOTE: decrease the max_iter and the steps!!!!!!!!!!!!!!!!!!!!!!!!!
SOLVER:
  STEPS: (63000, 64000, 108000, 432000)
  # MAX_ITER: 63000
  MAX_ITER: 65000

# NOTE: adjust SCALE_STEPS here!!!!!!!!!!!!!!!!!!!
SEMISUPNET:
  SCALE_STEPS: (60700, 61400, 62100, 62800, 63500, 64200) # [700, 1400, 2100, 2800, 3500, 4200]

VANISHING_POINT: "/home/aghosh/Projects/2PCNet/Datasets/VP/train_clear.json"

# PATH_BLUR: True
WARP_AUG_LZU: False


# USE_DEBUG: True
# TWO_PC_AUG: False
# AUG_PROB: 1.0
# WARP_DEBUG: True
NIGHTAUG: False
