# NOTE: use another yaml to reduce code
# _BASE_: "./acdc_11_6_baseline.yaml"
_BASE_: "./dense_snow_12_12_baseline.yaml"

# PATH_BLUR: True
WARP_AUG_LZU: True
WARP_FOVEA_INST: True


# USE_DEBUG: True
# TWO_PC_AUG: False
# AUG_PROB: 1.0
# WARP_DEBUG: True
NIGHTAUG: False

# NOTE: use this because currently no GPU left
SOLVER:
  STEPS: (65000, 75000, 80000, 432000)
  IMG_PER_BATCH_LABEL: 10 # 15
  IMG_PER_BATCH_UNLABEL: 10 # 15
  MAX_ITER: 97500

# NOTE: adjust SCALE_STEPS here!!!!!!!!!!!!!!!!!!!
SEMISUPNET:
  SCALE_STEPS: (65250, 70500, 75750, 81000, 86250) # [5250, 10500, 15750, 21000, 26250, 31500]